//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football.WinFormsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Football.WinFormsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove player from list of favourite players..
        /// </summary>
        internal static string dnd_text {
            get {
                return ResourceManager.GetString("dnd-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of favourite players.
        /// </summary>
        internal static string dnd_title {
            get {
                return ResourceManager.GetString("dnd-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to exit, do you want to save your changes before exiting?.
        /// </summary>
        internal static string exit_text {
            get {
                return ResourceManager.GetString("exit-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string exit_title {
            get {
                return ResourceManager.GetString("exit-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favourites.
        /// </summary>
        internal static string favourites_add {
            get {
                return ResourceManager.GetString("favourites-add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favourites.
        /// </summary>
        internal static string favourites_remove {
            get {
                return ResourceManager.GetString("favourites-remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching countries data, please wait....
        /// </summary>
        internal static string fetching_country_data {
            get {
                return ResourceManager.GetString("fetching-country-data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching matches data, please wait....
        /// </summary>
        internal static string fetching_football_data {
            get {
                return ResourceManager.GetString("fetching-football-data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fetched successfully....
        /// </summary>
        internal static string fetching_success {
            get {
                return ResourceManager.GetString("fetching-success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string Hr {
            get {
                return ResourceManager.GetString("Hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        internal static string player_captain {
            get {
                return ResourceManager.GetString("player-captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home: {0}, Away: {1}, Location: {2}, Attendance: {3}.
        /// </summary>
        internal static string print_matches_rank_format {
            get {
                return ResourceManager.GetString("print-matches-rank-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked matches:.
        /// </summary>
        internal static string print_matches_rank_title {
            get {
                return ResourceManager.GetString("print-matches-rank-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}, Shirt number: {1}, Position: {2}, Goals: {3}, Yellow cards: {4}.
        /// </summary>
        internal static string print_players_rank_format {
            get {
                return ResourceManager.GetString("print-players-rank-format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked players:.
        /// </summary>
        internal static string print_players_rank_title {
            get {
                return ResourceManager.GetString("print-players-rank-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranked information.
        /// </summary>
        internal static string print_title {
            get {
                return ResourceManager.GetString("print-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        internal static string select_country {
            get {
                return ResourceManager.GetString("select-country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
